CREATE TABLE cases (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    case VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    court VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
);
